name: HelpModifier
version: 2.0
author: applqpak
authors: [applqpak, TheNewHEROBRINEX, IceCruelStuff]
api: 3.14.0
main: HelpModifier\Main
commands:
  enablehelp:
    description: Enables help
    permission: help.enable

  disablehelp:
    description: Disables help
    permission: help.disable

permissions:
  help.enable:
    description: Allows user to use /enablehelp
    default: op

  help.disable:
    description: Allows user to use /disablehelp
    default: op
